#\DeclareLyXModule{Theorems (Extended, Numbered by Type within Chapters)}
#DescriptionBegin
#Defines some additional theorem environments for use with the
#AMS theorems packages. Includes Criterion, Algorithm, Axiom,
#Condition, Note, Notation, Summary, Acknowledgement, Conclusion,
#Assumption, and Case, in both numbered and non-numbered forms.
#Contrary to the plain Extended module, the different theorem
#types provided here each have a separate counter, restarted with each
#new chapter (e.g., criterion 1.1, criterion 1.2, axiom 1.1, assumption 1.1, #criterion 2.1, criterion 2.2, axiom 2.1..., as opposed to criterion 1,
#criterion 2, axiom 3, assumption 4...)
#DescriptionEnd
#Requires: theorems-ams-chap-bytype | theorems-chap-bytype

# Original Author : David L. Johnson <dlj0@lehigh.edu>
# Probably broken by Jean-Marc Lasgouttes <Jean-Marc.Lasgouttes@inria.fr>
# modified and modularized by Emmanuel GUREGHIAN <gureghia@boston.bertin.fr>
# Tinkered with Sep. '07 by Paul Rubin <rubin@msu.edu>
# Modularized Jan 08 by Richard Heck <rgheck@comcast.net>
# Hacked June '09 by Paul Rubin <rubin@msu.edu> to use separate counters
# Chapter dependence added Oct '16 by Andrew Parsloe <aparsloe@clear.net.nz>
# Edited sep '22 by Udi Fogiel <udifoglle@gmail.com>


Format 66


# The environnements defined (regular and starred) are :
# - Criterion
# - Algorithm
# - Axiom
# - Condition
# - Note
# - Notation
# - Summary
# - Acknowledgement
# - Conclusion
# - Assumption
# - Question

# We need separate counters for each theorem-like style.
Counter criterion
	Within         chapter
End
Counter algorithm
	Within         chapter
End
Counter axiom
	Within         chapter
End
Counter condition
	Within         chapter
End
Counter algorithm
	Within         chapter
End
Counter axiom
	Within         chapter
End
Counter condition
	Within         chapter
End
Counter note
	Within         chapter
End
Counter notation
	Within         chapter
End
Counter summary
	Within         chapter
End
Counter acknowledgement
	Within         chapter
End
Counter conclusion
	Within         chapter
End
Counter assumption
	Within         chapter
End
Counter question
	Within         chapter
End


Input theorems-extended.inc
Input theorems-refprefix.inc
Input theorems-labels.inc