#\DeclareLyXModule{Theorems (Extended)}
#DescriptionBegin
#Defines some additional theorem environments for use with the
#AMS theorems packages. Includes Criterion, Algorithm, Axiom,
#Condition, Note, Notation, Summary, Acknowledgement, Conclusion,
#Fact, Assumption, Case, and Question, in both numbered and non-numbered
#forms.
#DescriptionEnd
#Requires: theorems-ams | theorems
#Category: theorems

# Original Author : David L. Johnson <dlj0@lehigh.edu>
# Probably broken by Jean-Marc Lasgouttes <Jean-Marc.Lasgouttes@inria.fr>
# modified and modularized by Emmanuel GUREGHIAN <gureghia@boston.bertin.fr>
# Tinkered with Sep. '07 by Paul Rubin <rubin@msu.edu>
# Modularized Jan 08 by Richard Heck <rgheck@comcast.net>
# Edited sep '22 by Udi Fogiel <udifoglle@gmail.com>


Format 66

Input theorems-extended.inc
Input theorems-refprefix.inc