#\DeclareLyXModule{Theorems (AMS, Numbered by Chapter)}
#DescriptionBegin
#Defines theorem environments and the proof environment using the extended 
#AMS machinery. Both numbered and unnumbered types are provided. Contrary to the
#plain AMS Theorem module, the different theorem types provided here each have 
#a separate counter (e.g., theorem 1, theorem 2, lemma 1, proposition 1, theorem 3,
#lemma 2, ..., as opposed to theorem 1, theorem 2, lemma 3, proposition 4, ...).
#The numbering's scope is the whole document. For chapter- and section-wide numbering,
#use one of the 'within Sections'/'within Chapters' modules, respectively.
#DescriptionEnd
#Requires: theorems-ams
#Excludes: theorems-extended | theorems-ams-sec

# Original Author : Udi Fogiel <udifoglle@gmail.com>


Format 66

Counter theorem
	Within         chapter
End

Input theorems-base.inc
Input theorems-refprefix.inc
Input theorems-case.inc
Input theorems-proof.inc

Style Theorem
	Preamble
		\newcommand\lyx@newtheorem{\@ifstar{\newtheorem*}{\lyx@reg@newtheorem}}
		\newcommand\lyx@reg@newtheorem[2]{\newtheorem{#1}[thm]{#2}}
		\theoremstyle{plain}
		\ifcsname c@chapter\endcsname
			\ifx\c@chapter\relax
				\newtheorem{thm}{\protect\theoremname}
			\else
				\newtheorem{thm}{\protect\theoremname}[chapter]
			\fi
		\else
			\newtheorem{thm}{\protect\theoremname}
		\fi
	EndPreamble
End