#\DeclareLyXModule{Theorems (AMS, Numbered by Type within Sections)}
#DescriptionBegin
#Defines theorem environments and the proof environment using the extended
#AMS machinery. Both numbered and unnumbered types are provided. Contrary to the
#plain Theorem module, the different theorem types provided here each have a separate
#counter (e.g., theorem 1, theorem 2, lemma 1, proposition 1, theorem 3, lemma 2, ...,
#as opposed to theorem 1, theorem 2, lemma 3, proposition 4, ...). The numbering is reset
#at each section start.
#DescriptionEnd
#Requires: theorems-ams-bytype
#Excludes: theorems-extended-bytype | theorems-ams-chap-bytype

# Original Author : Udi Fogiel <udifoglle@gmail.com>


Format 66

# We need separate counters for each theorem-like style.
Counter theorem
	Within         section
End
Counter corollary
	Within         section
End
Counter lemma
	Within         section
End
Counter proposition
	Within         section
End
Counter conjecture
	Within         section
End
Counter fact
	Within         section
End
Counter definition
	Within         section
End
Counter example
	Within         section
End
Counter problem
	Within         section
End
Counter exercise
	Within         section
End
Counter remark
	Within         section
End
Counter claim
	Within         section
End


Style Theorem
	Preamble
		\newcommand\lyx@newtheorem{\@ifstar{\newtheorem*}{\lyx@reg@newtheorem}}
		\theoremstyle{plain}
		\ifcsname c@section\endcsname
			\ifx\c@section\relax
				\newcommand\lyx@reg@newtheorem[2]{\newtheorem{#1}{#2}}
				\newtheorem{thm}{\protect\theoremname}
			\else
				\newcommand\lyx@reg@newtheorem[2]{\newtheorem{#1}{#2}[section]}
				\newtheorem{thm}{\protect\theoremname}[section]
			\fi
		\else
			\newcommand\lyx@reg@newtheorem[2]{\newtheorem{#1}{#2}}
			\newtheorem{thm}{\protect\theoremname}
		\fi
	EndPreamble
End
